config/routes.rb
Rails.application.routes.draw do
  # devise（ユーザー認証）
  devise_for :users

  # タグのルーティング（検索・ツイート・CRUD）
  resources :tags, only: [:index, :new, :create, :destroy] do
    collection do
      get 'search', to: 'tags#search'       # タグ名による検索
    end
    get 'tweets', to: 'tweets#search'       # タグに紐づくツイート検索（必要なら）
  end

  # ユーザー
  resources :users, only: [:show]

  # ブログとツイート
  resources :blogs
  resources :tweets
  delete 'tweets/:id' => 'tweets#destroy'  # この行はresources :tweetsに含まれているので不要かも

  # ルートページ
  root to: 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    has_many :blog_tag_relations, dependent: :destroy
    has_many :tags, through: :blog_tag_relations, dependent: :destroy
end

app/models/blog_tag_relation.rb
class BlogTagRelation < ApplicationRecord
  belongs_to :blog
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_one_attached :image 
  validates :name, presence: true
  belongs_to :user

  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :blog_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :blogs, through: :blog_tag_relations, dependent: :destroy
  has_many :users, -> { distinct }, through: :blogs
  
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_one_attached :image 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one_attached :image 
  has_many :blogs, dependent: :destroy
  has_many :tags, -> { distinct }, through: :blogs
  # 🔽 自分が作成したタグ（←これを追加！）
  has_many :created_tags, class_name: 'Tag', foreign_key: 'user_id', dependent: :destroy

  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!

  def index
    @blogs = Blog.all
    if params[:tag_ids]
      @blogs = []
      params[:tag_ids].each do |key, value|
        @blogs += Tag.find_by(name: key).blogs if value == "1"
      end
      @blogs.uniq!
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
    @blog.tag_ids = Array(params.dig(:blog, :tag_ids))
  
    if params[:keyword].present?
      @tags = current_user.created_tags.where("name LIKE ?", "%#{params[:keyword]}%")
    else
      @tags = current_user.created_tags
    end
  end
  

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id

    if @blog.save
      redirect_to user_path(current_user), notice: '投稿が完了しました！'
    else
      if params[:keyword].present?
        @tags = current_user.created_tags.where("name LIKE ?", "%#{params[:keyword]}%")
      else
        @tags = current_user.created_tags
      end
      render :new
    end
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
    redirect_to action: :index
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @itirans = @tag.tweets.all
  end

  private

  def blog_params
    params.require(:blog).permit(:start_time, :image, :kion, :content, tag_ids: [])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  def index
    @tags = Tag.all
  end

  def new
    @tag = Tag.new
    @tags = current_user.created_tags
  end

  def search
    keyword = params[:keyword]
    puts "=== 検索キーワード: #{keyword}"  # ← 確認ログ
  
    if keyword.present?
      @tags = current_user.created_tags.where("name LIKE ?", "%#{keyword}%")
    else
      @tags = current_user.created_tags
    end
  
    @tag = Tag.new
    render :new
  end
  
  

  def create
    @tag = Tag.new(tag_params)
    @tag.user_id = current_user.id
    if @tag.save
      redirect_to new_tag_path, notice: 'タグを追加しました！'
    else
      render :new
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    
    if @tag.user_id == current_user.id
        @tag.destroy
        redirect_to new_tag_path, notice: 'タグを削除しました'
    else
        redirect_to new_tag_path, alert: '自分のタグしか削除できません'
    end

  end

  
  
  private
  def tag_params
    params.require(:tag).permit(:name, :image) # ← 写真もここでOK
  end
  



end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
        @tweets = Tweet.all
    end
    def new
    @tweet = Tweet.new
    end

  def create
    tweet = Tweet.new(tweet_params)
    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end
 
  
  private
  def tweet_params
    params.require(:tweet).permit(:kion, :review,:image )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # app/controllers/users_controller.rb
def show
  @user = User.find(params[:id])

  # タグ検索
  if params[:keyword].present?
    @tags = @user.created_tags.where("name LIKE ?", "%#{params[:keyword]}%")
  else
    @tags = @user.created_tags
  end

  # タグ絞り込み
  if params[:tag_ids].present?
    selected_ids = params[:tag_ids].select { |_id, v| v == "1" }.keys
    @blogs = @user.blogs.joins(:tags).where(tags: { id: selected_ids }).distinct
  else
    @blogs = @user.blogs
  end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/fasiohion_helper.rb
module FasiohionHelper
end

app/helpers/fasiohions_helper.rb
module FasiohionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="body-bg"style="color: white;">

<h1>みんなの日記</h1>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>


<br>

<%= link_to '日記をかく', new_blog_path %>


<%= month_calendar events: @blogs do |date, blogs_for_date| %>
  <div class="day-head"><%= date.day %></div>

  <% blogs_for_date.each do |blog| %>
        <% if blog.image.attached? %>
        <%= image_tag blog.image,
        style: "width: 100px; height: 100px; object-fit: cover; border-radius: 8px; display: block; margin: 0 auto;" %>
        <% end %>  

      <div class="cal-actions">
        <%= link_to "削除", blog,
              data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %>
        <%= link_to "詳細", blog_path(blog) %>
      </div>
    </div>
  <% end %>
<% end %>

<%= form_tag({controller:"blogs",action:"index"}, method: :get) do %>
    <% Tag.all.each do |t| %>
      <label class="tag-item">
        <%= check_box :tag_ids, t.name %>
        <% if t.image.attached? %>
          <%= image_tag t.image, size: "60x60" %>
        <% else %>
          <%= t.name %>  <!-- 画像が無い時は名前表示 -->
        <% end %>
        <span class="count">（<%= t.blogs.count %>）</span>
      </label>
    <% end %>
    <%= submit_tag '検索' %>
<% end %>

<%= link_to "新しいタグを追加", new_tag_path %>

app/views/blogs/new.html.erb
<div class="body-bg">
  <div class="page-nav" style="margin:16px 0;">
    <%= link_to "マイページへ", user_path(current_user) %>
  </div>

  <!-- ✅ 検索 + 投稿統合フォーム -->
<%= form_with url: new_blog_path, method: :get, local: true do %>
  <h2>タグを検索</h2>
  <%= text_field_tag :keyword, params[:keyword], placeholder: "タグ名を入力" %>

  <!-- 🔁 選択済みタグIDを hidden_field として送信 -->
  <% Array(@blog.tag_ids).each do |tag_id| %>
    <%= hidden_field_tag "blog[tag_ids][]", tag_id %>
  <% end %>

  <%= submit_tag "検索" %>
<% end %>


  <!-- ✍️ 投稿フォーム -->
  <%= form_with model: @blog, local: true do |form| %>
    <h2>タグを選択</h2>
    <div class="tag-selector">
      <% selected_tag_ids = Array(@blog.tag_ids).map(&:to_s) %>
      <% @tags.each do |tag| %>
        <label class="tag-option">
          <%= check_box_tag "blog[tag_ids][]", tag.id, selected_tag_ids.include?(tag.id.to_s), class: "hidden-checkbox", id: "tag_#{tag.id}" %>
          <% if tag.image.attached? %>
            <%= image_tag tag.image, class: "tag-image" %>
          <% else %>
            <div class="tag-name"><%= tag.name %></div>
          <% end %>
        </label>
      <% end %>
    </div>

    <!-- 日時 -->
    <div class="field">
      <%= form.label :start_time, "Date&Time" %>
      <%= form.datetime_select :start_time %>
    </div>

    <!-- 気温 -->
    <div class="kion">
      <%= form.label :kion, "Temperature (°C)" %>
      <%= form.text_field :kion, value: @blog.kion, step: 0.1 %>
    </div>

    <!-- コメント -->
    <div class="field">
      <%= form.label :content %>
      <%= form.text_field :content, value: @blog.content %>
    </div>

    <!-- 画像 -->
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>

    <!-- 送信ボタン -->
    <%= form.submit '送信' %>
  <% end %>

  <%= link_to "タグを編集", new_tag_path %>
</div>

app/views/blogs/show.html.erb
<div class="body-bg"style="color: white;">
<% if @blog.image.attached? %>
<%= image_tag @blog.image, style: "width: 150px; height: 150px; object-fit: cover; border-radius: 8px; display: block; margin-bottom: 10px;" %>
<% end %>


  

<p id="notice"><%= notice %></p>



<p><strong>Temperature:</strong>
  <%= @blog.kion.present? ? "#{@blog.kion}°C" : "-" %>
</p>



<p><strong>Date&Time:</strong>
  <%= @blog.start_time&.in_time_zone('Tokyo')&.strftime('%Y-%m-%d %H:%M') %>
</p>

<p><strong>Comment:</strong>
  <%= @blog.content.present? ? @blog.content : "-" %>
</p>


<p><strong>Tags:</strong></p>
<div style="display: flex; gap: 10px; flex-wrap: wrap;">
  <% @blog.tags.each do |t| %>
    <%= link_to tag_tweets_path(tag_id: t.id) do %>
      <% if t.image.attached? %>
        <%= image_tag t.image, size: "60x60", style: "border-radius: 8px;" %>
      <% else %>
        <span><%= t.name %></span> <!-- 画像がない場合のフォールバック -->
      <% end %>
    <% end %>
  <% end %>
</div>




<%= link_to 'Back to Calendar', user_path(current_user), class: 'btn btn-secondary' %>
</div>

app/views/layouts/application.html.erb
<div class="body-bg">
  <div class="page-nav" style="margin:16px 0;">
<!DOCTYPE html>
<html>
  <head>
    <title>Fasiohion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<body>
 <header>
  
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>


  <body>
    <%= yield %>
  </body>
</html>

</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/index.html.erb
<h2>タグ一覧</h2>

<%= link_to "新しいタグを追加", new_tag_path %>

<ul>
  <% @tags.each do |tag| %>
    <li>
      <% if tag.image.attached? %>
        <%= image_tag(tag.image, size: "50x50") %>
      <% end %>
      <%= tag.name %>
    </li>
  <% end %>
</ul>
<%= link_to 'Back', blogs_path %>

app/views/tags/new.html.erb
<div class="body-bg"style="color: white;">
<h2>タグを新しく追加</h2>

<%= form_with model: @tag do |f| %>
  <div>
    <%= f.label :name, "タグ名" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :image, "タグ画像" %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "登録" %>
<% end %>

<%= link_to '日記をかく', new_blog_path, class: 'btn btn-primary' %>
<%= link_to 'マイページへ', user_path(current_user), class: 'btn btn-secondary' %>

<h2>タグを検索</h2>
<%= form_tag search_tags_path, method: :get do %>
  <%= text_field_tag :keyword, params[:keyword], placeholder: "タグ名を入力" %>
  <%= submit_tag "検索" %>
<% end %>


<h2>登録済みタグ一覧</h2>

<ul>
<% @tags.each do |tag| %>
    <li style="margin-bottom: 10px;">
      <% if tag.image.attached? %>
        <%= image_tag tag.image, size: "60x60" %>
      <% else %>
        <%= tag.name %>
      <% end %>

      <%= tag.name %>

      <%= link_to '削除', tag_path(tag),
                  data: { turbo_method: :delete, turbo_confirm: 'このタグを削除してもよろしいですか？' },
                  class: 'btn btn-danger' %>
    </li>
  <% end %>
<ul>
  

</div>

app/views/tweets/index.html.erb
<h1>自分の題名</h1>
<h3>一覧ページ</h3>
<%= link_to "新規投稿へ", new_tweet_path %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
        <% if t.image.attached? %>
            <%= image_tag t.image, size: '250x200'%>
        <% end %>
    
        <% t.tags.each do |tag| %>
        <%= link_to tag.name, tag_tweets_path(tag_id: tag.id) %>
    <% end %>
       
      <%= t.kion %>
      <%= t.review %>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>(自分の題名)</h1>
<h3>新規投稿ページ</h3>




  

<%= link_to "一覧に戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="body-bg"style="color: white;">

  <!-- マイページの内容 -->
<h1>マイページ</h1>

<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<% if @user.image.attached? %>
  <%= image_tag @user.image, size: '125x100' %>
<% end %>

<hr>



<h2>自分の日記</h2>
<%= link_to '日記をかく', new_blog_path %>

<%= month_calendar events: @blogs do |date, blogs_for_date| %>
  <div class="day-head"><%= date.day %></div>

  <% blogs_for_date.each do |blog| %>
    <div class="blog-entry">
      <% if blog.image.attached? %>
        <%= image_tag blog.image, size: '100x100' %>
      <% end %>

      <div class="cal-actions">
        <%= link_to "削除", blog,
              data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %>
        <%= link_to "詳細", blog_path(blog) %>
      </div>
    </div>
  <% end %>
<% end %>

<%= link_to "みんなのカレンダーへ", blogs_path %>

</div>


<!-- タグを検索 -->
<h2>タグ検索</h2>
<%= form_with url: user_path(@user), method: :get, local: true do |f| %>
  <%= text_field_tag :keyword, params[:keyword], placeholder: "タグ名を入力" %>
  <%= submit_tag "検索" %>
<% end %>

<!-- タグで絞り込み -->
<%= form_with url: user_path(@user), method: :get, local: true do %>
  <% @tags.each do |tag| %>
    <% count = tag.blogs.where(user_id: @user.id).count %>
    <label style="display:inline-block; margin:8px; text-align:center;">
      <%= check_box_tag "tag_ids[#{tag.id}]", "1", params.dig(:tag_ids, tag.id.to_s) == "1" %>
      <% if tag.image.attached? %>
        <%= image_tag tag.image, size: "60x60", style: "display:block; margin-bottom:4px;" %>
      <% else %>
        <%= tag.name %>
      <% end %>
      <br>
      <span style="font-size:12px; color:gray;">（≒ <%= count %> 回）</span>
    </label>
  <% end %>

  <div style="margin-top: 10px;">
    <%= submit_tag "絞り込み" %>
  </div>
<% end %>